server:
  port: 8083

spring:
  application:
    name: rocketmq-producer

rocketmq:
  name-server: ${name-server}
  producer:
    group: producer-group-1
    send-message-timeout: 6000
    retry-times-when-send-failed: 2